### ISSUE TITLE
Orlando Exchange quartet lists 5 members

### ISSUE THREAD

**Issue by russkibass** [dbinetti/barberscore#172]
Need to remove David Hauptman listed as 2nd bari in Groups - Orlando exchange.  David is not listed in BHS database

**Comment by russkibass** [comment]
This may be a more complicated issue. Easy Street lists even more but without the year when a particular member stepped in it's impossible to say which 4 members competed when

**Comment by dbinetti** [comment]
actually, this may be fixed in the new release.  but i'll leave open for now.

to explain, there will be two different -- but related -- concepts of membership.  At the highest level there is a group, which has members which change through time.  (IE, Forefront the Group, which switched tenors from Garry to Drew, or Vocal Majority, switching Directors from Greg to Jeff.)  We want to keep all that.

Then, there are Performers, which are groups that perform at a contest with four guys on stage (or a director(s)).  those guys will be constant, and not change.

**Comment by russkibass** [comment]
I think I saw that fixed, forgot for which quartet where there were more than 5 members but they were linked to a specific performance which showed when the change occured

**Comment by dbinetti** [comment]
right, so they switched a member.  we'll have a better way of dealing with
this moving forward

**Comment by dbinetti** [comment]
Switched the member to inactive.  Closing

**Comment by russkibass** [comment]
Already got it

-- 
Alexander Boltenko 
"Russki" Bass, St. Petersburg, FL
russkibass@barbershopharmony.org
@RusskibassTampa
singing bass with the Heralds of Harmony
Cell 269-501-SING (7464)
http://barberscore.com - best International contests tracker & database
"Barbershop quartet singing is four guys tasting the holy essence of four individual mechanisms coming into complete agreement."  (Meredith Willson)
